### ISSUE TITLE
upgrade to latest docker 1.7.0

### ISSUE THREAD

**Issue by ivankravchenko** [progrium/dokku#1295] opened 2015-07-09 10:22 UTC
Hello. I've tried to install dokku (commented out docker 1.6.2 installation, then `make install`) with official docker 1.7.0 pre-installed. It seems like it works.
So I request to update dokku to use docker 1.7.0.

**Comment by michaelshobbs** [comment] 2015-07-09 15:39
there is still a major incompatibility with many of the most popular dokku plugins and docker 1.7.0. I think the community will need/want to work on refactoring those plugins before we remove the pin to 1.6.2.

**Comment by michaelshobbs** [comment] 2015-07-09 15:43
You can also just set `$DOCKER_VERSION` when building dokku from the Makefile.

**Comment by ivankravchenko** [comment] 2015-07-09 16:31
@michaelshobbs, thank you for pointing at `DOCKER_VERSION`!

**Comment by michaelshobbs** [comment] 2015-07-31 16:54
https://github.com/docker/docker/issues/14293

**Comment by vincentfretin** [comment] 2015-08-02 08:57
When you'll update docker, you should use the new apt repository, the package is now docker-engine, see http://blog.docker.com/2015/07/new-apt-and-yum-repos

**Comment by rcarmo** [comment] 2015-08-07 08:47
It might be best to aim for 1.7.1/1.8, actually.

**Comment by dmr** [comment] 2015-08-17 06:44
1.8 is out. Did anybody test it yet?

**Comment by josegonzalez** [comment] 2015-08-17 15:11
No, but if you'd like to and can report back, that would be great.

**Comment by andrewsomething** [comment] 2015-08-17 16:04
The behavior is the same with Docker 1.8. How can we move forward with this? Is there a list of plugins that should be considered essential to get fixed before unblocking this?

There's an open pull request against dokku-pg-plugin that would resolve this for that plugin, though Kloadut seems to have gone inactive:

https://github.com/Kloadut/dokku-pg-plugin/pull/78/

**Comment by tilgovi** [comment] 2015-08-24 22:38
Would be great if anyone could provide a list of plugins. Or, I can help assemble such a list if someone can spell out what incompatibilities we need to be on the lookout for.

**Comment by josegonzalez** [comment] 2015-08-25 03:19
@tilgovi you may want to check out #1408,which provides "official" plugins that should allow usage with 1.7+ (I'm running the latest 1.7 and will shortly upgrade to 1.8).

**Comment by Flink** [comment] 2015-08-26 12:14
So far I’ve tested and validated the following plugins with docker 1.8 and dokku 0.3.26:
* [dokku-psql-single-container](https://github.com/Flink/dokku-psql-single-container)
* [my fork of dokku-forego](https://github.com/Flink/dokku-forego)
* [dokku-airbrake-deploy](https://github.com/Flink/dokku-airbrake-deploy)
* [my fork of dokku-memcached-plugin (jezdez)](https://github.com/Flink/dokku-memcached-plugin)
* [dokku-slack](https://github.com/ribot/dokku-slack)
* [dokku-mariadb (krisrang)](https://github.com/krisrang/dokku-mariadb)
* [dokku-docker-auto-volumes](https://github.com/Flink/dokku-docker-auto-volumes)
* [dokku-http-auth](https://github.com/Flink/dokku-http-auth)
* [dokku-maintenance](https://github.com/Flink/dokku-maintenance)
* [dokku-named-containers](https://github.com/Flink/dokku-named-containers)
* [dokku-redis-plugin (sekjun9878)](https://github.com/sekjun9878/dokku-redis-plugin)
* [dokku-logspout](https://github.com/michaelshobbs/dokku-logspout)

/cc @tilgovi @josegonzalez

**Comment by josegonzalez** [comment] 2015-08-26 14:03
@flink are you checking all plugins? Mind making a PR to the plugins.MD to state that these plugins work with master?

**Comment by Flink** [comment] 2015-08-26 14:06
No I only checked those we use in production. I’ve made PR for some (mainly new help syntax and to change deprecated hooks). I checked against dokku 0.3.26, if master hasn’t changed much it should be ok I think :)

**Comment by josegonzalez** [comment] 2015-08-26 14:08
We're those prs merged?

**Comment by Flink** [comment] 2015-08-26 14:11
not at the moment but they’re not impacting compatibility with docker 1.8 (just help syntax and deprecated hooks that still work with latest stable dokku)

**Comment by josegonzalez** [comment] 2015-08-26 14:25
Okay. Well any deprecated usage is certainly going to break in the next release, which we're planning on being 0.4.0 (ripping off the bandaids). Are those repos actively maintained?

**Comment by Flink** [comment] 2015-08-26 14:30
There’s PR for slack, redis, logspout and mariadb. logspout is @michaelshobbs so I think it’ll be updated soon :)
Slack & mariadb I don’t know, redis is @sekjun9878 and it seems that he don’t actively maintain his repo anymore.

**Comment by josegonzalez** [comment] 2015-08-26 14:31
Which version of forego is linked to in the docs?

**Comment by Flink** [comment] 2015-08-26 14:33
Not my fork. But the original repo seems dead (last commit january).

**Comment by Flink** [comment] 2015-08-26 14:38
Well @sekjun9878 just merged my PR :+1: :grin:

**Comment by Flink** [comment] 2015-08-28 12:57
@krisrang and @michaelshobbs also updated their plugin :) Only waiting for @ribot to merge.

**Comment by Flink** [comment] 2015-09-01 14:04
PR for Slack has been merged too :)

**Comment by josegonzalez** [comment] 2015-09-01 15:16
@Flink mind updating the plugins doc to say those have been tested with the latest stable?

**Comment by Flink** [comment] 2015-09-01 15:19
Not at all, will do!

**Comment by tilgovi** [comment] 2015-09-10 23:40
What's left for this?

**Comment by josegonzalez** [comment] 2015-09-10 23:45
A 0.4.0 release which we're currently working towards. We need to update the following files to refer to the updated apt repo/packages:

- `bootstrap.sh`
- `debian/control`
- `Makefile`

And also merge in the doc changes for the new official dokku datastore plugins, which depends upon plugn, which is currently being worked on.

**Comment by josegonzalez** [comment] 2015-09-15 20:44
Closing as there is an open PR for this.

**Closed by josegonzalez** 2015-09-15 20:44 UTC
Labels: 0.4.0, upstream-issue

**Comment by longhotsummer** [comment] 2015-09-16 06:40
Could we keep this open until the PR is merged please? It's not actually fixed until the PR is merged. :)

**Comment by dmr** [comment] 2015-09-16 07:19
What's missing for 0.4.0? Is the current master what you call 0.4.0?

**Comment by tilgovi** [comment] 2015-09-16 19:04
@longhotsummer follow the trail. GitHub shows the backreference to #1467. Go there and click "subscribe".

I understand where you're coming from and been through this thought a number of times. Ultimately, the most important thing is that the maintainers can tell what's going on and move forward with the least overhead. If it's simpler for them to close the issue, then the issue is closed. If you want to follow along, there's enough information to do so.

@dmr I suspect https://github.com/progrium/dokku/labels/0.4.0 is roughly what remains, and then master would be tagged.

**Comment by josegonzalez** [comment] 2015-09-16 22:01
Master is master, and you shouldn't be using that for day-to-day installs unless you're feeling lucky :)

We have a few prs to merge, and when they are done, I will release master.
