### ISSUE TITLE
Dokku v0.3.10 - ! [remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by andykenward** [progrium/dokku#841] opened 2014-12-23 20:28 UTC
Fresh install of Dokku and I still cant get an app to deploy when pushing. Here is the log output

https://gist.github.com/andykenward/8f815099c679bcfbad14

**Comment by lgierth** [comment] 2015-01-12 03:04
I'm seeing what seems to be the same issue on e0c49ec724f5daa2d2fdd57cad9ca8529147faea, with dokku-buildpack-jekyll-nginx and this repo: https://github.com/lgierth/lars.meshnet.berlin

https://gist.github.com/andykenward/8f815099c679bcfbad14#comment-1370409

**Comment by lgierth** [comment] 2015-01-12 03:08
> Verify network connectivity from the container perhaps?

I can't get DNS to work from within a container, so far. ICMP pings work.

**Comment by lgierth** [comment] 2015-01-12 03:36
Okay, got it, for me it was a matter of uncommenting `DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4` in `/etc/default/docker`.

**Comment by josegonzalez** [comment] 2015-01-12 03:40
I wonder if we can use our docker-args pluginhook to set this in our vms without modifying the default docker file. @michaelshobbs thoughts?

**Comment by michaelshobbs** [comment] 2015-01-12 04:08
It's definitely feasible. However I don't think we should dictate DNS servers.

**Comment by josegonzalez** [comment] 2015-01-12 04:22
Why not? The alternative is having a shitty experience for our users. If anything, we can default to those options and let users override them where desired?

**Comment by michaelshobbs** [comment] 2015-01-12 15:41
Yeah it's probably fine as long as we clearly document it and provide a simple way to override them.

**Comment by rchrd2** [comment] 2015-01-12 23:29
I am having this same issue, but uncommenting `DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 in /etc/default/docker` did not solve it. Could anybody please shed some light on this? What specifically is failing? Everything was running smoothly for me last week and now it just stopped working? Does dokku depend on external libraries that could change, such as buildpacks?

I am running dokku v0.3.12. Trying to deploy nodejs, which appears to have been updated a very recently <https://github.com/heroku/heroku-buildpack-nodejs/releases>. Does dokku pull the latest buildpacks by default?

**Comment by rchrd2** [comment] 2015-01-13 04:38
Here's an update to my debugging. I was able to confirm that the issue has to do with the content of my repository. Thus, this seems like a bug. Why would the files in a repo break dokku? In this case, the files are just a basic website (javascript, css, html, images).

**Comment by michaelshobbs** [comment] 2015-01-13 05:01
A deployment log with tracing on would probably help

**Comment by rchrd2** [comment] 2015-01-13 05:02
I broke down the steps to confirm that it is this one file (with a crazy long name) that is breaking it. See gist: https://gist.github.com/rchrd2/76d439ad07bd87d556f2.

(trace coming soon)

**Comment by michaelshobbs** [comment] 2015-01-13 05:10
Interesting. Must be in the git-receive hook. Can you please open a new issue as I believe the root causes to be quite different? Thanks!

**Comment by simenbrekken** [comment] 2015-01-20 13:37
I've run into a similar problem just now, it solved itself by rebooting the VPS (Rackspace). Very strange.

Failed push: https://gist.github.com/7a12be929ad06373c556
Successful push (after reboot): https://gist.github.com/simenbrekken/7a12be929ad06373c556#file-02-trace-log

**Comment by michaelshobbs** [comment] 2015-01-20 19:27
Seems almost certainly a (transient) networking issue of some sort.

**Comment by josegonzalez** [comment] 2015-01-20 19:47
I'm guessing heroku uses an http proxy for s3 requests like this. I wonder if we could do similar and have a command that downloads requirements to the box during installation? *shrug*

**Comment by michaelshobbs** [comment] 2015-01-22 23:19
@josegonzalez that seems like significant complexity though. do you think that should even be a concern of dokku?

**Comment by josegonzalez** [comment] 2015-01-22 23:21
No, I guess not. Do you mind updating docs with potential fixes for this issue and closing this one out?

**Comment by michaelshobbs** [comment] 2015-01-22 23:43
Updating docs with what now?

**Comment by josegonzalez** [comment] 2015-01-22 23:44
Stuff like:

- Check your docker dns
- Try running the command inside the container
- Try deploying again - it may be a transient issue with upstream

*shrug*

**Closed** 2015-01-23 01:32 UTC

**Comment by rdetert** [comment] 2015-07-30 04:34
Yeah this was the issue for me as well. I accidentally had the `.git` folder from a third party cloned repo inside a subfolder of my main repo. *facepalm*
