### ISSUE TITLE
dokku_log_info1 does not seem to output from hooks except the last one

### ISSUE THREAD

**Issue by cjblomqvist** [progrium/dokku#1157] opened 2015-04-29 18:21 UTC
Turns out that if you have two plugins which uses the same hook, and you use dokku_log_info1 to output some debugging messages (or something else), only the last hook's dokku_log_info1 will get outputted.

To follow up on IRC discussion with @josegonzalez - it was not that the hooks didn't get triggered, it was just the messages that didn't get outputed (I checked that the others got executed using dokku trace on like you suggested - very neat trick!).

I've been fighting the consequences of this for a little bit too long to have the energy to file a proper issue with repro steps. I thought it'd be nice to have it documented here though for any possible people ending up with the same issue. You may close it if you don't want to dig more into this.

**Comment by michaelshobbs** [comment] 2015-04-29 20:54
Are we sure its `dokku_log_info1` and not `dokku_log_info1_quiet`? Can we at least get a deploy with dokku trace on?

**Comment by cjblomqvist** [comment] 2015-04-30 07:49
Actually, I realized I still had some output left from doing exactly that: https://gist.github.com/cjblomqvist/d81e5f0e250deac05c59

Check out rows 381, 388 and 397. Only the 397 command actually triggered any output.

**Comment by michaelshobbs** [comment] 2015-04-30 17:25
I'm not sure the expected behavior here and the title of this issue is, I think, vastly misleading. We see output from many (perhaps not all) plugin hooks. It looks like the testing @cjblomqvist did was in receive-app. I've attempted to reproduce based on what I see in the gist. All seems to log as expected. (Lines with [DEBUG] are all in `plugins/git/commands` and `plugins/git/receive-app`)

What am I missing?

```
$ git push dokku@dokku.me:node-js-app master
Pseudo-terminal will not be allocated because stdin is not a terminal.
Counting objects: 418, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (335/335), done.
Writing objects: 100% (418/418), 214.96 KiB | 0 bytes/s, done.
Total 418 (delta 66), reused 392 (delta 51)
remote: -----> [DEBUG] git-hook
remote: -----> [DEBUG] about to call pluginhook receive-app: 84cfc82ae8e8b8b96e054c4f58c2a0b7337ec3c2 - refs/heads/master
remote: -----> [DEBUG] SOME TESTING! RECEIVE_APP
remote: -----> [DEBUG] GIT-BUILD: git-build - node-js-app - 84cfc82ae8e8b8b96e054c4f58c2a0b7337ec3c2
remote: -----> [DEBUG] about to call git_build_app_repo
-----> Cleaning up...
-----> Building node-js-app from buildstep...
-----> Adding BUILD_ENV to build environment...
-----> Fetching custom buildpack
-----> Node.js app detected
-----> Resetting git environment
-----> Requested node range: ^0.10.0
-----> Resolved node version: 0.10.38
-----> Downloading and installing node
-----> Exporting config vars to environment
-----> Installing dependencies
       express@4.12.3 node_modules/express
       ├── merge-descriptors@1.0.0
       ├── utils-merge@1.0.0
       ├── cookie-signature@1.0.6
       ├── methods@1.1.1
       ├── cookie@0.1.2
       ├── fresh@0.2.4
       ├── escape-html@1.0.1
       ├── range-parser@1.0.2
       ├── finalhandler@0.3.4
       ├── content-type@1.0.1
       ├── vary@1.0.0
       ├── parseurl@1.3.0
       ├── serve-static@1.9.2
       ├── content-disposition@0.5.0
       ├── path-to-regexp@0.1.3
       ├── depd@1.0.1
       ├── qs@2.4.1
       ├── on-finished@2.2.1 (ee-first@1.1.0)
       ├── etag@1.5.1 (crc@3.2.1)
       ├── send@0.12.2 (destroy@1.0.3, ms@0.7.0, mime@1.3.4)
       ├── proxy-addr@1.0.7 (forwarded@0.1.0, ipaddr.js@0.1.9)
       ├── debug@2.1.3 (ms@0.7.0)
       ├── accepts@1.2.5 (negotiator@0.5.1, mime-types@2.0.10)
       └── type-is@1.6.1 (media-typer@0.3.0, mime-types@2.0.10)
-----> Caching node_modules directory for future builds
-----> Cleaning up node-gyp and npm artifacts
-----> Building runtime environment
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing node-js-app...
-----> Deploying node-js-app...
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 35 seconds ...
-----> Default container check successful!
=====> node-js-app container output:
       > node-js-sample@0.1.0 start /app
       > node index.js
       Node app is running at localhost:5000
=====> end node-js-app container output
-----> Running post-deploy
-----> Creating new /home/dokku/node-js-app/VHOST...
-----> Configuring node-js-app.dokku.me...
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
=====> Application deployed:
       http://node-js-app.dokku.me

To dokku@dokku.me:node-js-app
 * [new branch]      master -> master
```

**Comment by cjblomqvist** [comment] 2015-05-04 09:28
Hmm, are you having the same plugin hook in multiple plugins? Or do you have one plugin outputting content in different plugin hooks? Only the first scenario caused trouble for me.

Or am I misinterpreting you?

E.g. repro steps should be something along:
1. Install dokku. 
2. Create 2 plugins, each with a receive-app hook. 
3. In each hook, add dokku_log_info1 "Something" 
4. When deploying applications, "Something" only gets outputted once.

Or did you already try that?

**Comment by michaelshobbs** [comment] 2015-05-04 15:40
Oh I see. I didn't realize you had two `recieve-app` plugins. I think the issue is in the nature of how `receive-app` is used in dokku. I do know that multiple `pre/post-build/deploy/etc` pluginhooks work just fine. I'll see if I can debug further now that I understand the scenario better.

However, I'm not sure I understand the use-case of two receive-app hooks. Can you elaborate there?

**Comment by cjblomqvist** [comment] 2015-05-04 15:44
Two receive-app hooks actually works - the code in both hooks actually gets triggered. Just that dokku_info_log1 doesn't output any content in any such statements except the last receive-app -hook's one.

The scenario in this case is that receive-app is the only place we can gather the SHA1 of the commit. Thus we need one receive-app in the dokku-git-rev -plugin (to gather the SHA1 and save for later - for the post-release hook) and one for the actual receive-app hook (the one in the git plugin that ensures deployment is done). This works good, except that if you want to output some messages in both receive-app hooks, you'll only get one message.

**Comment by michaelshobbs** [comment] 2015-05-04 15:54
Oh ok. Can I get a gist of your `receive-app` hook?

**Comment by cjblomqvist** [comment] 2015-05-04 15:57
Unfortunately I don't have them anymore for the above output (gist). But I know I tested with more or less only having the following code: https://gist.github.com/cjblomqvist/7487f803f646b54de343

**Comment by michaelshobbs** [comment] 2015-05-04 16:21
This is potentially a pluginhook issue....

Test case
plugins/00_testing/receive-app
```
#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

APP="$1"; REV="$2"

dokku_log_info1 "[DEBUG:00_testing:receive-app] $APP: $REV"
echo "[DEBUG:00_testing:receive-app] $APP: $REV"
exit 0
```

plugins/00_testing/post-deploy
```
#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

APP="$1"; PORT="$2"; IP="$3"
dokku_log_info1 "[DEBUG:00_testing:post-deploy] $APP $PORT $IP"
echo "[DEBUG:00_testing:post-deploy] $APP $PORT $IP"
```

plugins/git/receive-app
```
#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

APP="$1"; REV="$2"

dokku_log_info1 "[DEBUG:git:receive-app] $APP: $REV"
echo "[DEBUG:git:receive-app] $APP: $REV"
dokku git-build $APP $REV
```

plugins/nginx-vhosts/post-deploy
```
#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

APP="$1"; PORT="$2"; IP="$3"
NO_VHOST=$(dokku config:get $APP NO_VHOST || true)

if [[ -n "$NO_VHOST" ]]; then
  dokku_log_info1 "NO_VHOST config detected"
elif [[ ! -f "$DOKKU_ROOT/$APP/VHOST" ]]; then
  dokku domains:setup $APP
fi

dokku_log_info1 "[DEBUG:nginx-vhosts:post-deploy] $APP $PORT $IP"
echo "[DEBUG:nginx-vhosts:post-deploy] $APP $PORT $IP"
dokku nginx:build-config $APP $PORT $IP
```

Running a `git push...` or a `dokku ps:rebuild ...` both yield echo/dokku_log_info1 output from only the last (lexigraphically sorted) plugin.

**Comment by michaelshobbs** [comment] 2015-05-04 16:22
@progrium any thoughts on this?

**Comment by michaelshobbs** [comment] 2015-05-04 17:37
related: https://github.com/progrium/pluginhook/issues/3

**Comment by josegonzalez** [comment] 2015-08-26 04:43
@michaelshobbs would plugn fix this issue? I think so, right?

**Comment by michaelshobbs** [comment] 2015-08-26 16:02
I believe that to be the case if I recall correctly from the plugn work done in #1228. I'll be picking that up again this week or early next.

**Comment by josegonzalez** [comment] 2015-08-26 16:55
Yeah, closing then since there is an open PR for this.

**Closed by josegonzalez** 2015-08-26 16:55 UTC
Labels: documentation, upstream-issue
