### ISSUE TITLE
remote: mktemp: failed to create directory via template

### ISSUE THREAD

**Issue by bogdanrn** [progrium/dokku#1272] opened 2015-07-03 09:15 UTC
remote: mktemp: failed to create directory via template '/tmp/buildpacks/custom/meteor-XXXX': Permission denied

This is the error i get when i try to deploy a meteor app with this buildpack https://github.com/AdmitHub/meteor-buildpack-horse . I did a fresh meteor-test app and i have the same problem with it. I saw in the history someone had the same issue and he ended up not using dokku anymore. ( i want to keep use it :smile: )

**Comment by michaelshobbs** [comment] 2015-07-03 14:50
related #1214 #1112

**Comment by nicksergeant** [comment] 2015-07-06 16:34
This is also a duplicate of this issue: https://github.com/progrium/dokku/issues/1048 -- I added a bunch of additional reproduction steps there, as well.

**Comment by michaelshobbs** [comment] 2015-07-06 16:39
@bogdanrn

The buildpack custom path was an issue with buildstep I thought. Can you build it from scratch and try again?

0. Destroy any running apps and run `dokku cleanup`
1. `docker rmi progrium/buildstep`
2. `BUILD_STACK=true make stack`
3. deploy app
4. Profit :smile:

**Comment by bogdanrn** [comment] 2015-07-16 14:10
@michaelshobbs Thanks, it worked.

**Comment by michaelshobbs** [comment] 2015-07-27 16:56
new buildstep release is out and dokku is updated.

**Closed by michaelshobbs** 2015-07-27 16:56 UTC
Labels: buildstep, upstream-issue
