### ISSUE TITLE
Deploy fails after "fetching custom buildpack"

### ISSUE THREAD

**Issue by sampettersson** [progrium/dokku#1063] opened 2015-03-27 17:35 UTC
I am having some issues deploying a specific app, the app is written in Node.JS and needs a custom buildpack with grunt support, I made a fork of the buildpack and simply changed "heroku" to "dokku".

My fork is available here: https://github.com/sampettersson/dokku-grunt-buildpack

I am successfully deploying apps using that exact same buildpack, but for one single app deploy always fail and "docker ps -a" reports "exit (128)". I did an extensive search trying any solutions I found to this problem, but none of them have worked so far.

I can confirm that:
A: DNS is working.
B: I can CURL from all my docker containers.
C: The exact same buildpack is working for other apps.
D: Destroying and redeploying doesn't make a difference.
E: Changing the name of the app doesn't make a difference.

Here is the full log of the deployment process: https://gist.github.com/sampettersson/66faf0ca0ce3525d4ba6

Thanks!

**Comment by michaelshobbs** [comment] 2015-03-27 17:49
I know github has been dealing with a DDOS attack today. Perhaps related?

**Comment by sampettersson** [comment] 2015-03-27 17:52
I thought that was the case at first, I took the buildpack and uploaded to a local git repo hosted in a gogs (https://github.com/gogits/gogs) docker container but this didn't work either.

And in that case shouldn't the other app's that depend on the same buildpack fail too?

**Comment by michaelshobbs** [comment] 2015-03-27 18:32
Yes, of course. I wasn't sure if you had tried the others in the same timeframe. When you say it didn't work in the gogs container, can you provide anymore info than 'it didn't work?' Any error message? What does your `.env` file look like? Perhaps `cat -E .env` just to make sure there isn't anything weird there.

**Comment by sampettersson** [comment] 2015-03-27 22:50
As far as I can see the output of the `git push` is the same for both Gogs and Github, also tried to clone from both Github and Gogs within the build container which worked as expected.

this is the output of `cat -e .env`: `export BUILDPACK_URL=https://gogs.pusselbit.com/sam/dokku-grunt-buildpack.git`

**Comment by michaelshobbs** [comment] 2015-03-28 07:22
You'll need to jump into a container and do some more digging. If I were you, I'd use the image created after the one that runs `/build/builder` and attempt to these two "scripts" and see what sort of output we get.

```
cd /tmp/buildpacks
rm -rf custom
/build/install-buildpack /tmp/buildpacks https://github.com/sampettersson/dokku-grunt-buildpack custom 
```
and
```
cd /tmp/buildpacks
rm -rf custom
/build/install-buildpack /tmp/buildpacks https://gogs.pusselbit.com/sam/dokku-grunt-buildpack.git custom 
```

**Comment by sampettersson** [comment] 2015-03-28 08:27
Tried to run the commands in all of the images that are created on deploy, but all of them gave me `bash: /build/install-buildpack: No such file or directory` exactly which image are I'm supposed to run this on?

Also after running `/build/builder` in the `dokku/testing:latest` image, no `custom` folder is created in `/tmp/buildpacks`.

**Comment by michaelshobbs** [comment] 2015-03-28 16:30
What version of buildstep?

**Comment by sampettersson** [comment] 2015-03-28 19:59
Cloned and updated yesterday, thought that an old version could be the culprit but that doesn't seem to be the case. I can also add that pushing the app to heroku works as it should.

**Comment by michaelshobbs** [comment] 2015-03-28 20:21
Just to confirm, I was able to use the original buildpack url with the latest buildstep in my local dev environment.

**Comment by sampettersson** [comment] 2015-03-28 20:23
Yeah the buildpack doesn't seem to be the problem at all, which is really confusing.

**Comment by michaelshobbs** [comment] 2015-03-28 20:23
Is there a disk space issue perhaps on this host?

**Comment by michaelshobbs** [comment] 2015-03-28 20:24
@progrium how do we get more verbosity out of the `/bin/herokuish buildpack build` command?

**Comment by sampettersson** [comment] 2015-03-28 20:28
Ubuntu reports 164GB of available space on `/`, so disk space should not be an issue.

**Comment by michaelshobbs** [comment] 2015-03-28 20:29
Assuming there are no other partitions then, ya?

**Comment by sampettersson** [comment] 2015-03-28 20:30
Here's the complete output of `df -h`.

```
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/paas--vg-root  189G   16G  164G   9% /
none                       4.0K     0  4.0K   0% /sys/fs/cgroup
udev                       3.9G  4.0K  3.9G   1% /dev
tmpfs                      798M  416K  798M   1% /run
none                       5.0M     0  5.0M   0% /run/lock
none                       3.9G  3.2M  3.9G   1% /run/shm
none                       100M     0  100M   0% /run/user
/dev/sda1                  236M   98M  126M  44% /boot
```

**Comment by michaelshobbs** [comment] 2015-03-28 20:37
Looks legit. Unfortunately, I'm not sure how to get more info on why `herokuish` is failing.... @josegonzalez you have any thoughts here?

**Comment by sampettersson** [comment] 2015-03-28 21:04
Did a fresh clone of the repo I was working in, changed some things to support pushing to dokku and to my surprise everything ran smoothely. Will try to look into the differences between the two repos to see what may have been causing the issues.

**Comment by michaelshobbs** [comment] 2015-03-28 21:44
Sounds good. Let us know if you find any more info.

**Comment by mozillamonks** [comment] 2015-03-29 17:03
I'm having the same issue when  trying to use custom buildpacks as well. Even using the [static test](https://github.com/progrium/dokku/tree/master/tests/apps/static) in a new repo will fail. Using the latest version of dokku on DO (used the Dokku preset on DO, then ran the [upgrade instructions](https://github.com/progrium/dokku/blob/master/docs/upgrading.md) since it was a version behind).

```
remote:        -----> Fetching custom buildpack
remote: + exit_code=128
remote: + set -e
remote: + '[' 128 -eq 10 ']'
remote: + implemented=1
...etc...
```

Also get `bash: /build/install-buildpack: No such file or directory` when trying to debug steps listed.

**Comment by alex88** [comment] 2015-04-01 09:34
I was getting the same error with the buildpack set as `https://github.com/ddollar/heroku-buildpack-multi.git`

I've ran the docker container and I've seen that using https url github was requesting username and using `git@` git was asking for remote key acceptance

**Comment by alex88** [comment] 2015-04-01 09:38
Update: Seems the issue is with the .env file, since it doesn't have a new newline at the end of it the .env file with the CURL settings appended looks like:

```
export BUILDPACK_URL= https://github.com/ddollar/heroku-buildpack-multi.gitexport CURL_CONNECT_TIMEOUT=5
export CURL_TIMEOUT=30
```

this breaks the buildpack url variable and so the fetch of the custom buildpack

**Comment by alex88** [comment] 2015-04-01 09:41
Maybe changing https://github.com/progrium/dokku/blob/master/plugins/build-env/pre-build#L9-L10 with a `\n` before the export

**Comment by josegonzalez** [comment] 2015-04-01 15:49
@alex88 this is fixed in the latest dokku release. If you are on Digital Ocean, you can simply do the following to upgrade:

```shell
sudo apt-get install dokku
```

Recent Digital Ocean servers use debian packages for installation :)

**Comment by alex88** [comment] 2015-04-01 15:54
@josegonzalez iirc I had dokku upgraded with the git pull command, anyway, adding a newline worked here

**Comment by josegonzalez** [comment] 2015-04-01 16:22
Well, if you're running 0.3.16, then a deploy should fix the issue.

**Comment by michaelshobbs** [comment] 2015-04-01 16:57
Yeah, this was supposed to be fixed by https://github.com/progrium/dokku/pull/1026 which is in 0.3.16.

**Comment by michaelshobbs** [comment] 2015-04-01 16:58
What's left to be done here?

**Comment by josegonzalez** [comment] 2015-04-01 19:54
Nothing except verify that this isn't an issue in 0.3.16.

**Comment by michaelshobbs** [comment] 2015-04-01 20:49
ref #1025 #1026

**Closed** 2015-04-03 19:18 UTC
