### ISSUE TITLE
dokkus nginx-vhost plugin should make nginx access.log and error.log available via a command

### ISSUE THREAD

**Issue by fwolfst** [progrium/dokku#1159] opened 2015-04-30 15:05 UTC
Hey guys,
really happy with my dokku experience, but I'd like an addition to the nginx(-vhost) plugin, building on https://github.com/progrium/dokku/issues/1158:

Provide access to the respective logs, like

    $ dokku nginx:access-log myapp
    $ dokku nginx:access-log myapp -t
    $ dokku nginx:error-log -t

I hope its relatively clear what I mean :)

**Comment by fwolfst** [comment] 2015-04-30 15:08
Thinking about it, the logs probably rotate already, so implementation has to take that into account.

**Comment by isundaylee** [comment] 2015-07-29 18:19
Thinking about log rotation, what should the expected behavior be (with and without rotation)? 

`-t` behavior should be relatively straightforward. It should probably just behave like `tail -F`, which starts reading from the new log file whenever the log file is replaced (due to rotation). But what should the behavior without `-t` be? 

I have used Dokku for a while, but have never contributed before. If no one else has started working on this, I can take a shot and implement this, once the expected behavior has been settled. It should be a relatively easy task.

**Comment by josegonzalez** [comment] 2015-07-29 18:25
Without the flag? Just show the last N lines, where N could be 20.

**Comment by isundaylee** [comment] 2015-07-29 18:27
Suppose access-someapp.log only has 10 lines, should it show those 10 lines, as well as 10 additional lines from access-someapp.log.1?

**Comment by josegonzalez** [comment] 2015-07-29 18:39
Nope, just the current file.

**Comment by fwolfst** [comment] 2015-07-29 18:40
I agree, start out simple, show max. 20 lines. Probably just invoke `tail` without any arguments...

**Comment by isundaylee** [comment] 2015-07-29 19:01
Ok. I can take this on. Should I just fork, work, and submit PR?

**Comment by josegonzalez** [comment] 2015-07-29 19:34
Sure.

**Comment by isundaylee** [comment] 2015-07-30 07:21
Seems like `dokku` user doesn't have any permission on `/var/log/nginx`. Cannot even `ls` there. Is that normal? If so, should I `sudo`? 

```bash
dokku@dokku:/var/log$ ls -l
...
drwxr-x--- 2 www-data adm     4096 Jul 30 06:56 nginx
...
dokku@dokku:/var/log$ ls -l nginx
ls: cannot open directory nginx: Permission denied
```

**Comment by isundaylee** [comment] 2015-07-30 07:48
Submitted PR #1352 under the assumption that we can allow `sudo tail` for `dokku` user. I'll modify it if we decide to go other ways to solve the permission issue.

**Comment by fwolfst** [comment] 2015-07-30 09:32
Awesome, thanks @isundaylee 
I have two further thoughts:
 * before issueing the tail, you could `echo` the path to the file shown ( ~ `echo "# Showing logs from "$NGINX_LOGS_PATH""`
 * Somewhere it has to be said that the **default path** for the log files is assumed (or parse the actual nginx-configuration and try to determine which log file is actually used - but that surely is more difficult). Just to protect users who edited the nginx.conf/template.

**Comment by michaelshobbs** [comment] 2015-07-30 15:35
I like the idea of parsing the config file for the file paths and default to `/var/log/nginx/...` if it's not found.

**Comment by isundaylee** [comment] 2015-07-30 22:52
I like the idea of parsing logs location from nginx conf. I'll do that! 

Meanwhile, @michaelshobbs, that means we cannot limit the `/usr/bin/tail` entry in the sudoers file any further right? Since the log files can theoretically be anywhere.

**Comment by michaelshobbs** [comment] 2015-07-30 23:03
If we can't limit the sudoers line to a file pattern, I don't think this will fly. As it stands, this allows anyone with access to the dokku user to tail any file.

**Comment by isundaylee** [comment] 2015-07-31 02:51
hmm then we will have to arbitrarily limit the nginx log files to be in some particular locations. 

any workaruonds?

**Comment by michaelshobbs** [comment] 2015-07-31 03:14
I think choosing a standard log location, documenting the benefits of placing them there and then letting the user decide in the end is probably a decent compromise.

**Comment by isundaylee** [comment] 2015-07-31 03:15
does that mean we are not supporting nginx:access|error-logs commands for non-standard log locations?

**Comment by fwolfst** [comment] 2015-07-31 06:53
For the default locations, maybe changing the `/etc/logrotate.d/nginx` -rule and adjust the user is enough (untried). I dont like the idea soooo much, as its quite tricky and a not so obvious change.

**Comment by michaelshobbs** [comment] 2015-07-31 16:50
@fwolfst what do you mean?

**Comment by fwolfst** [comment] 2015-08-01 12:10
@michaelshobbs It was a comment about working around the elevated dokku permissions (`sudo`). Aim was to change the owner of nginx log file. Afaics this is possible either via the nginx `user` directive or by a respective logrotate configuration.

**Comment by isundaylee** [comment] 2015-08-02 23:56
@fwolfst so I think for nginx to be able to bind to `:80` it has to run as root right? (correct me if I'm wrong here). 

Regarding the potential solution involving `logrotate.d` rules, does it work on logs that are not rotated yet (i.e., the current log file)? 

Actually, the root cause here is because the directory containing the log file `/var/log/nginx` has permission `---` as world permission. The log files themselves have `r--`, and should be fine for `dokku` to read. 

So should we do a `chmod` somewhere on `/var/log/nginx` to allow everyone read access to it? Just another idea to think about.

**Comment by josegonzalez** [comment] 2015-08-26 04:47
Closing as there is a pr opened to fix this issue.

**Closed by josegonzalez** 2015-08-26 04:47 UTC
Labels: enhancement

**Comment by isundaylee** [comment] 2015-08-26 04:50
I think there is still an ongoing discussion here on how to deal with/bypass the permission issue?

**Comment by josegonzalez** [comment] 2015-08-26 04:51
We can take care of that discussion in the PR, no?

**Comment by isundaylee** [comment] 2015-08-26 04:52
Yeah sure. I was saying that I am not sure about how to proceed on modifying the PR since we haven't reached a conclusion on the permission issue. :)

**Comment by josegonzalez** [comment] 2015-08-26 04:52
I think @michaelshobbs commented as to your solution in the PR. Once you modify that tail, our current configuration should be just fine.

**Comment by isundaylee** [comment] 2015-08-26 04:53
@josegonzalez  meaning that we're not supporting custom log directories for now?

**Comment by josegonzalez** [comment] 2015-08-26 04:55
I think moving logs from `/var/log/nginx` sounds like a bad idea. It's non-standard, would break existing tooling, and be annoying for users who are familiar with nginx.
