### ISSUE TITLE
error installing 0.3.18

### ISSUE THREAD

**Issue by sglebs** [progrium/dokku#1196] opened 2015-05-19 11:22 UTC
0.3.17 installs ok, but 0.3.17 gives an error at the end under Ubuntu 14.04 LTS at Digital Ocean:

```
Preconfiguring packages ...
(Reading database ... 93254 files and directories currently installed.)
Preparing to unpack .../dokku_0.3.18_amd64.deb ...
Error: keyfile '/root/.ssh/id_rsa.pub' not found.
       you can enter a new keyfile path when you restart the installation.
dpkg: error processing archive /var/cache/apt/archives/dokku_0.3.18_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/dokku_0.3.18_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@web-sites:~# 
```

The dpkg logs:

```
root@web-sites:~# tail /var/log/dpkg.log 
2015-05-19 07:11:58 status unpacked sshcommand:amd64 0.0.1
2015-05-19 07:11:58 status half-configured sshcommand:amd64 0.0.1
2015-05-19 07:11:58 status installed sshcommand:amd64 0.0.1
2015-05-19 07:11:58 trigproc libc-bin:amd64 2.19-0ubuntu6.6 <none>
2015-05-19 07:11:58 status half-configured libc-bin:amd64 2.19-0ubuntu6.6
2015-05-19 07:11:58 status installed libc-bin:amd64 2.19-0ubuntu6.6
2015-05-19 07:12:00 startup archives unpack
2015-05-19 07:12:00 install dokku:amd64 <none> 0.3.18
2015-05-19 07:12:00 status half-installed dokku:amd64 0.3.18
2015-05-19 07:12:00 status not-installed dokku:amd64 <none>
root@web-sites:~# 
```

**Comment by dsapoetra** [comment] 2015-06-18 04:59
i'm getting the same result here, just tried to install today

**Comment by michaelshobbs** [comment] 2015-06-18 05:38
@dsapoetra any visibility into what's going on? Steps to reproduce? Any detail on your starting point?

**Comment by avanlaningham** [comment] 2015-06-20 17:26
I got this error too, and just did a ssh-keygen -t rsa in my host.  I ubuntu 14.0.4 and previously installed docker other than that it was cliean.

**Comment by joshco** [comment] 2015-06-21 01:16
I saw this as well. For me it failed because there is no root ssh key config.  This can happen on a new server instance on services that use alternate user accounts.   Eg, EC2 with ubuntu will have the admin ssh in via ubuntu, not root.  If you try to ssh in as root, it will give you an error like "Please log in with ubuntu not root"

I think it may be to much for dokku to expect a working SSH key config for root in order to install itself.

**Comment by josegonzalez** [comment] 2015-06-24 00:56
This should be fixed in latest master. Cutting a release now.

**Comment by hzhu** [comment] 2015-06-24 05:17
Same issue, on EC2. Did the latest release to master fix it for you guys who are using Digital Ocean?

**Comment by josegonzalez** [comment] 2015-06-24 18:34
I just pushed 0.3.19 debian packages, can someone try those and let me know if there are any issues?

**Closed** 2015-06-25 15:17 UTC
