### ISSUE TITLE
Dokku scaled Web instead of Worker when my Procfile had worker only

### ISSUE THREAD

**Issue by paezao** [progrium/dokku#1442] opened 2015-09-04 20:47 UTC
Hello,

Dokku tried scaling web instead of worker even though my Procfile only had a worker configured.

Procfile contents:
`
worker: bundle exec ruby app.rb
`

Deploy trace gist:
https://gist.github.com/anonymous/560f163e99c9326dd549

**Comment by michaelshobbs** [comment] 2015-09-08 14:46
What version of dokku/docker are you running?

**Comment by michaelshobbs** [comment] 2015-09-08 14:57
It looks like it found a `DOKKU_SCALE` file at `/home/dokku/unrealengine-irc-bot/DOKKU_SCALE`. Had you deployed this app previously with a different Procfile or do you have a `DOKKU_SCALE` file checked into your app repo?

**Comment by josegonzalez** [comment] 2015-09-08 15:09
His first deploy failed, but the `DOKKU_SCALE` file was generated before it failed, so the next deploy picked up this (invalid) `DOKKU_SCALE` file.

**Comment by michaelshobbs** [comment] 2015-09-08 15:20
@paezao I would run `dokku apps:destroy unrealengine-irc-bot` and deploy again or run `dokku ps:scale unrealengine-irc-bot web=0 worker=1`

**Comment by josegonzalez** [comment] 2015-09-08 15:26
@michaelshobbs that still doesn't fix the fact that the DOKKU_SCALE is generated without respect to what is in the `Procfile`. When generating that, if the `Procfile` exists and doesn't have a `web` process, we should just have everything scaled to 0, and no web process, right?

**Comment by michaelshobbs** [comment] 2015-09-16 22:34
What is the expected behavior? Originally we said if the user doesn't tell us how to scale then we default to `web=1`. 

I've made the docs more clear (hopefully) in #1471. Let me know if you guys think we should something more here.

**Comment by michaelshobbs** [comment] 2015-09-16 22:42
Ah! Just re-read @josegonzalez's comment. If we do what you suggested, then what would be expected to happen in the end? Spit an error out and quit?

**Comment by michaelshobbs** [comment] 2015-09-16 22:47
For reference @josegonzalez :smile: 
https://github.com/progrium/dokku/pull/1118#issuecomment-95033595

**Comment by josegonzalez** [comment] 2015-09-16 22:51
Maybe just a doc change and thats it.

**Comment by michaelshobbs** [comment] 2015-09-16 23:01
For the record, heroku does complete the app deployment successfully but does not start the worker. I can mirror this behavior if we think it's worthwhile.

**Comment by michaelshobbs** [comment] 2015-09-16 23:05
@paezao so the ultimate answer to your scenario as dokku stands right now, is to ship a `DOKKU_SCALE` file in your repo that only has `worker=1` in it.

**Comment by michaelshobbs** [comment] 2015-09-16 23:06
@josegonzalez by default heroku will inspect your Procfile and set `web=1` and everything else to 0.

**Comment by josegonzalez** [comment] 2015-09-16 23:07
We should mirror what heroku does in this case.

**Comment by michaelshobbs** [comment] 2015-09-16 23:07
Ok will do.

**Comment by josegonzalez** [comment] 2015-09-16 23:07
@michaelshobbs you could also:

- `dokku apps:create APP`
- `dokku ps:scale worker=1 web=0`
- deploy

Right?

**Comment by michaelshobbs** [comment] 2015-09-16 23:08
That is another way to do it yes

**Closed** 2015-09-17 03:44 UTC
Labels: bug
