### ISSUE TITLE
How to correctly fire up background processor?

### ISSUE THREAD

**Issue by Corstiaan84** [progrium/dokku#1721] opened 2015-11-26 13:11 UTC
This is a more of a question than an issue :-).

Im very new to managing unix servers and deploying rails apps (coming from .net...). Last couple of days have been the usual rollercoaster of curiosity -> potential -> effort -> frustration -> panic -> questioning existential existence -> break through -> repeat. In the process I learned the basics of deploying rails apps with ubuntu, unicorn, nginx, postgres and capistrano. However, I never got my setup 98% the way I wanted so I went back to Dokku, which is easy but abstracts away most of the bits that make up the stack. Any way, Dokku does exactly what I want/need so sticking with Dokku so far.

One thing that is getting away from me is how to run worker processes for, in my case, postgres + queue_classic. I am reading some contradictionary things out there and not all plugins, like shoreman, play nice with Dokku 0.4.4. Can anyone tell me how the basic steps to getting this working?

Thank you for your time. Dokku is really, really, REALLY cool :-).

**Comment by riccardoa** [comment] 2015-11-26 14:22
+1
shoreman don't seems to work with dokku 0.4.5

and this stuff is really messed up in the dokku world...why there isn't a official way ? something like this:
https://github.com/progrium/buildstep/pull/43

**Comment by michaelshobbs** [comment] 2015-11-26 15:07
That is supported in dokku. Check out the process scaling documentation.

**Comment by Corstiaan84** [comment] 2015-11-26 15:29
Hi @michaelshobbs. Yes, I have looked at the docs and added a DOKKU_SCALE file, but I get "dokku Error response from daemon: Cannot kill container" when trying to deploy my app. Any ideas? :-)

**Comment by michaelshobbs** [comment] 2015-11-26 15:36
Can you please add the requested info from our contributing doc? Also include a gist of your failing deployment with dokku trace on.

**Comment by Corstiaan84** [comment] 2015-11-26 15:47
Here's the gist: https://gist.github.com/Corstiaan84/ed67c470a81059b3bd73

Need some guidance regarding the contributing doc. What you you need from me exactly? :-)

**Comment by riccardoa** [comment] 2015-11-26 15:54
@michaelshobbs I didn't noticed it :( sorry btw I can confirm that it works(just tested!)

**Comment by riccardoa** [comment] 2015-11-26 16:05
Ok @Corstiaan84 I reply here because it's better...sorry if I can't create a gist, but I don't have much time right now.
I've simply followed these steps:
http://progrium.viewdocs.io/dokku/application-deployment/ (until http://progrium.viewdocs.io/dokku/application-deployment/#deploy-the-app)
Then I've installed redis from the official plugin:
https://github.com/dokku/dokku-redis (create a redis db, then link it with the web app)
after that I've created a DOKKU_SCALE file like it's explained here: http://progrium.viewdocs.io/dokku/process-management/
(create the dokku_scale file inside your web app!!!)

After that I've set up the configuration variables( http://progrium.viewdocs.io/dokku/configuration-management/ that I need for my app/workers) and then I've deployed.

**Comment by riccardoa** [comment] 2015-11-26 16:05
I suggest that you test all these steps in a clear vps.

**Comment by michaelshobbs** [comment] 2015-11-26 16:11
@Corstiaan84 Was referring to this: https://github.com/progrium/dokku/blob/master/CONTRIBUTING.md

**Comment by michaelshobbs** [comment] 2015-11-26 16:14
Your deploy is failing due to your app containers not staying alive

**Comment by riccardoa** [comment] 2015-11-26 16:16
@michaelshobbs sorry  I did not understand - deleted comments.

**Comment by michaelshobbs** [comment] 2015-11-26 16:25
@riccardoa can you be more specific regarding your documentation suggestion?

**Comment by Corstiaan84** [comment] 2015-11-26 16:25
Hi @michaelshobbs I created the contribution info here: https://gist.github.com/Corstiaan84/df0ae20c7cbaf268f23a

"Your deploy is failing due to your app containers not staying alive" => Ok, thanks. What would be a solution for this?

**Comment by michaelshobbs** [comment] 2015-11-26 16:28
You'll need to debug why your app is failing to start. You can see exited containers with `docker ps -a` and see their output with `docker logs <container_id_from_docker_ps>`

**Comment by michaelshobbs** [comment] 2015-11-26 16:28
Additionally can you share your `Procfile` and `DOKKU_SCALE` file contents?

**Comment by riccardoa** [comment] 2015-11-26 16:40
@michaelshobbs  I think that here http://progrium.viewdocs.io/dokku/application-deployment/ should be explained that dokku like heroku, only load the web from Procfile and for have workers running, you should use a DOKKU_SCALE file.

**Comment by michaelshobbs** [comment] 2015-11-26 16:43
@riccardoa a `DOKKU_SCALE` file is not required. By default, we will run 1 container for each process defined in the supplied `Procfile`

**Comment by Corstiaan84** [comment] 2015-11-26 16:46
@michaelshobbs 

Procfile:
web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
worker: bundle exec rake qc:work QUEUES="default,mailers"

DOKKU_SCALE
web=1
worker=1

With these file in the root, the deploy finished with this message:
-----> Running post-deploy
remote: Error response from daemon: no such id: everseller.web.1
remote: Error: failed to rename container named everseller.web.1

**Comment by michaelshobbs** [comment] 2015-11-26 16:50
That seems like different behavior from the original gist. This renaming issue should be fixed in dokku 0.4.5. For reference: https://github.com/progrium/dokku/pull/1707

**Comment by Corstiaan84** [comment] 2015-11-26 16:53
Yes, correct. Sorry -- should have mentioned that. The original gist was without the "worker: bundle exec rake qc:work QUEUES="default,mailers"" line from the proc file...

**Comment by michaelshobbs** [comment] 2015-11-26 16:53
Ok. Try upgrading to dokku 0.4.5 and let us know.

**Comment by Corstiaan84** [comment] 2015-11-26 17:14
Updating leads to a succesful deploy!! :-). Thanks for sticking with me. Now got some new errors but those are specific to my code and not relevant to this issue.

**Comment by michaelshobbs** [comment] 2015-11-26 17:15
Sounds good. I'll close this out then.

**Closed by michaelshobbs** 2015-11-26 17:15 UTC
