### ISSUE TITLE
Domains automatically added after enabling SSL

### ISSUE THREAD

**Issue by olalonde** [progrium/dokku#1405] opened 2015-08-22 08:25 UTC
Is there any way to disable this feature? I have two dokku apps which share the same multi domain SSL certificate though they are both distinct apps. Right now, if I add the SSL certificate to any app, it always automatically adds the main domain of the certificate which is not what I want.

**Comment by josegonzalez** [comment] 2015-08-22 10:10
At the moment, I believe the only fix is to create a custom nginx configuration for your application.

Note, I *think* this is a duplicate of #1368. The solution to that should also solve this I think.

**Closed by josegonzalez** 2015-08-22 10:10 UTC

**Comment by olalonde** [comment] 2015-08-22 16:09
Yep, seems like a duplicate. I created a custom nginx config for the moment.
